version: "3.7"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mongodb_container
    networks:
      default:
      internal:
    stdin_open: true
    tty: true

  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    restart: always
    volumes:
      - mongodb_data_container:/data/db
    networks:
      internal:

volumes:
  mongodb_data_container:

networks:
    default:
    internal:
      internal: true